import type { Metadata } from "next";
import { Lato, Caveat } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
  weight: "variable",
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${caveat.variable} ${lato.variable} grid grid-rows-[4em_1fr_2em] antialiased min-h-screen p-2 transition-all duration-150`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
